CREATE DATABASE dw;

\c dw

-- ----------------------------
-- DIMENSÕES
-- ----------------------------

CREATE TABLE dim_tempo (
    id_dim_tempo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    dia INT NOT NULL,
    mes INT NOT NULL,
    nome_mes VARCHAR(20) NOT NULL,
    trimestre INT NOT NULL,
    ano INT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    flag_fim_semana BOOLEAN NOT NULL,
    UNIQUE (data)
);

CREATE TABLE dim_enderecos (
    id_dim_endereco INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_endereco_original VARCHAR(50),
    tipo_endereco VARCHAR(45),
    nome_logradouro VARCHAR(255),
    cep VARCHAR(20),
    nome_bairro VARCHAR(255),
    regiao_cidade VARCHAR(255),
    nome_cidade VARCHAR(255),
    nome_estado VARCHAR(100),
    sigla_uf VARCHAR(10),
    pais VARCHAR(100) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_endereco_original)
);

CREATE TABLE dim_produtos (
    id_dim_produto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_produto_original VARCHAR(50) NOT NULL,
    nome_produto VARCHAR(255) NOT NULL,
    nome_categoria VARCHAR(255),
    valor NUMERIC(15,2),
    moeda CHAR(3) NOT NULL DEFAULT 'BRL',
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_produto_original)
);

CREATE TABLE dim_cliente (
    id_dim_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_cliente_original VARCHAR(50) NOT NULL,
    tipo_pessoa VARCHAR(20) NOT NULL,
    nome_cliente VARCHAR(255) NOT NULL,
    sexo VARCHAR(20),
    faixa_renda VARCHAR(50),
    estado_civil VARCHAR(45),
    faixa_etaria VARCHAR(20),
    ano_nascimento INT,
    nome_profissao VARCHAR(255),
    ddd_principal VARCHAR(10),
    tipo_telefone VARCHAR(50),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_cliente_original)
);

CREATE TABLE dim_funcionario (
    id_dim_funcionario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_funcionario_original VARCHAR(50),
    nome_funcionario VARCHAR(255) NOT NULL,
    cargo VARCHAR(255),
    data_contratacao DATE,
    cidade VARCHAR(255),
    pais VARCHAR(100),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_funcionario_original)
);

INSERT INTO dim_funcionario (id_dim_funcionario, sistema_origem, id_funcionario_original, nome_funcionario, cargo)
VALUES (-1, 'N/A', NULL, 'Não aplicável', 'Não aplicável');

CREATE TABLE dim_transportadora (
    id_dim_transportadora INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_transportadora_original VARCHAR(50),
    nome_transportadora VARCHAR(255) NOT NULL,
    telefone VARCHAR(50),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_transportadora_original)
);

INSERT INTO dim_transportadora (id_dim_transportadora, sistema_origem, id_transportadora_original, nome_transportadora)
VALUES (-1, 'N/A', NULL, 'Não aplicável');

-- ----------------------------
-- FATOS
-- ----------------------------

CREATE TABLE fato_vendas (
    id_fato_venda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_venda_original VARCHAR(50) NOT NULL,
    id_item_original VARCHAR(50),
    id_dim_tempo INT NOT NULL REFERENCES dim_tempo (id_dim_tempo),
    id_dim_cliente INT NOT NULL REFERENCES dim_cliente (id_dim_cliente),
    id_dim_produto INT NOT NULL REFERENCES dim_produtos (id_dim_produto),
    id_dim_endereco INT NOT NULL REFERENCES dim_enderecos (id_dim_endereco),
    id_dim_funcionario INT NOT NULL DEFAULT -1 REFERENCES dim_funcionario (id_dim_funcionario),
    id_dim_transportadora INT NOT NULL DEFAULT -1 REFERENCES dim_transportadora (id_dim_transportadora),
    tipo_venda VARCHAR(50),
    quantidade INT NOT NULL,
    valor_unitario NUMERIC(15,2) NOT NULL,
    valor_desconto NUMERIC(15,2) NOT NULL DEFAULT 0,
    valor_total_item NUMERIC(15,2) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_fato_vendas_tempo ON fato_vendas (id_dim_tempo);
CREATE INDEX idx_fato_vendas_cliente ON fato_vendas (id_dim_cliente);
CREATE INDEX idx_fato_vendas_produto ON fato_vendas (id_dim_produto);
CREATE INDEX idx_fato_vendas_endereco ON fato_vendas (id_dim_endereco);
CREATE INDEX idx_fato_vendas_funcionario ON fato_vendas (id_dim_funcionario);
CREATE INDEX idx_fato_vendas_transportadora ON fato_vendas (id_dim_transportadora);

CREATE TABLE fato_compras (
    id_fato_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL DEFAULT 'Mercearia',
    id_compra_original VARCHAR(50) NOT NULL,
    id_item_original VARCHAR(50),
    id_dim_tempo INT NOT NULL REFERENCES dim_tempo (id_dim_tempo),
    id_dim_cliente INT NOT NULL REFERENCES dim_cliente (id_dim_cliente),
    id_dim_produto INT NOT NULL REFERENCES dim_produtos (id_dim_produto),
    id_dim_endereco INT NOT NULL REFERENCES dim_enderecos (id_dim_endereco),
    quantidade INT NOT NULL,
    valor_unitario NUMERIC(15,2) NOT NULL,
    valor_total_item NUMERIC(15,2) NOT NULL,
    lead_time_dias INT,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_fato_compras_tempo ON fato_compras (id_dim_tempo);
CREATE INDEX idx_fato_compras_cliente ON fato_compras (id_dim_cliente);
CREATE INDEX idx_fato_compras_produto ON fato_compras (id_dim_produto);
CREATE INDEX idx_fato_compras_endereco ON fato_compras (id_dim_endereco);

-- ----------------------------
-- POPULAÇÃO DA DIM_TEMPO
-- ----------------------------

INSERT INTO dim_tempo (data, dia, mes, nome_mes, trimestre, ano, dia_semana, flag_fim_semana)
SELECT
    d::date,
    EXTRACT(DAY FROM d)::int,
    EXTRACT(MONTH FROM d)::int,
    TO_CHAR(d, 'TMMonth'),
    EXTRACT(QUARTER FROM d)::int,
    EXTRACT(YEAR FROM d)::int,
    TO_CHAR(d, 'TMDay'),
    EXTRACT(ISODOW FROM d) IN (6, 7)
FROM generate_series('1996-01-01'::date, '2025-12-31'::date, interval '1 day') AS d;
