\c dw

INSERT INTO metadados.sistema_transacional (id_sistema, nome_sistema, descricao, plataforma) VALUES
(1, 'Mercearia', 'Sistema transacional de vendas e compras de uma mercearia', 'MySQL 8.4'),
(2, 'Northwind', 'Sistema transacional de vendas por atacado de uma distribuidora de alimentos', 'PostgreSQL 16');

INSERT INTO metadados.tipo_campo (id_tipo_campo, nome_tipo_campo, descricao) VALUES
(1, 'Inteiro', 'Valores numéricos inteiros'),
(2, 'Texto', 'Cadeias de caracteres'),
(3, 'Data', 'Datas sem hora'),
(4, 'Data/Hora', 'Datas com hora (timestamp)'),
(5, 'Decimal', 'Valores numéricos com casas decimais'),
(6, 'Booleano', 'Valores lógicos (verdadeiro/falso)'),
(7, 'Binário', 'Dados binários (imagens, arquivos)');

INSERT INTO metadados.tabela_transacional (id_tabela, id_sistema, nome_tabela, descricao) VALUES
(1, 1, 'Uf', 'Tabela transacional do sistema Mercearia'),
(2, 1, 'Cidades', 'Tabela transacional do sistema Mercearia'),
(3, 1, 'Profissoes', 'Tabela transacional do sistema Mercearia'),
(4, 1, 'Bairros', 'Tabela transacional do sistema Mercearia'),
(5, 1, 'Logradouros', 'Tabela transacional do sistema Mercearia'),
(6, 1, 'Enderecos', 'Tabela transacional do sistema Mercearia'),
(7, 1, 'Pessoas', 'Tabela transacional do sistema Mercearia'),
(8, 1, 'Telefones', 'Tabela transacional do sistema Mercearia'),
(9, 1, 'Categorias', 'Tabela transacional do sistema Mercearia'),
(10, 1, 'Produtos', 'Tabela transacional do sistema Mercearia'),
(11, 1, 'Compras', 'Tabela transacional do sistema Mercearia'),
(12, 1, 'Itens_compras', 'Tabela transacional do sistema Mercearia'),
(13, 1, 'Vendas', 'Tabela transacional do sistema Mercearia'),
(14, 1, 'Itens_Vendas', 'Tabela transacional do sistema Mercearia'),
(15, 2, 'categories', 'Tabela transacional do sistema Northwind'),
(16, 2, 'customer_customer_demo', 'Tabela transacional do sistema Northwind'),
(17, 2, 'customer_demographics', 'Tabela transacional do sistema Northwind'),
(18, 2, 'customers', 'Tabela transacional do sistema Northwind'),
(19, 2, 'employees', 'Tabela transacional do sistema Northwind'),
(20, 2, 'employee_territories', 'Tabela transacional do sistema Northwind'),
(21, 2, 'order_details', 'Tabela transacional do sistema Northwind'),
(22, 2, 'orders', 'Tabela transacional do sistema Northwind'),
(23, 2, 'products', 'Tabela transacional do sistema Northwind'),
(24, 2, 'region', 'Tabela transacional do sistema Northwind'),
(25, 2, 'shippers', 'Tabela transacional do sistema Northwind'),
(26, 2, 'suppliers', 'Tabela transacional do sistema Northwind'),
(27, 2, 'territories', 'Tabela transacional do sistema Northwind'),
(28, 2, 'us_states', 'Tabela transacional do sistema Northwind');

INSERT INTO metadados.campo_transacional (id_campo, id_tabela, id_tipo_campo, nome_campo, descricao, mascara_campo, tamanho_campo, casa_decimal) VALUES
(1, 1, 1, 'ID_UF', NULL, NULL, NULL, NULL),
(2, 1, 2, 'NOME_ESTADO', NULL, NULL, NULL, NULL),
(3, 1, 2, 'SIGLA', NULL, NULL, NULL, NULL),
(4, 2, 1, 'ID_CIDADE', NULL, NULL, NULL, NULL),
(5, 2, 2, 'NOME_CIDADE', NULL, NULL, NULL, NULL),
(6, 2, 1, 'ID_UF', NULL, NULL, NULL, NULL),
(7, 3, 1, 'ID_PROFISSAO', NULL, NULL, NULL, NULL),
(8, 3, 2, 'NOME_PROFISSAO', NULL, NULL, NULL, NULL),
(9, 4, 1, 'ID_BAIRRO', NULL, NULL, NULL, NULL),
(10, 4, 2, 'NOME_BAIRRO', NULL, NULL, NULL, NULL),
(11, 4, 2, 'REGIAOCIDADE', NULL, NULL, NULL, NULL),
(12, 4, 1, 'ID_CIDADE', NULL, NULL, NULL, NULL),
(13, 5, 1, 'ID_LOGRADOURO', NULL, NULL, NULL, NULL),
(14, 5, 1, 'TIPO', NULL, NULL, NULL, NULL),
(15, 5, 2, 'LOGRADOURO', NULL, NULL, NULL, NULL),
(16, 5, 1, 'CEP', NULL, NULL, NULL, NULL),
(17, 5, 1, 'NUMEROINICIAL', NULL, NULL, NULL, NULL),
(18, 5, 1, 'NUMEROFINAL', NULL, NULL, NULL, NULL),
(19, 5, 1, 'ID_BAIRRO', NULL, NULL, NULL, NULL),
(20, 6, 1, 'ID_ENDERECO', NULL, NULL, NULL, NULL),
(21, 6, 1, 'ID_PESSOA', NULL, NULL, NULL, NULL),
(22, 6, 1, 'ID_LOGRADOURO', NULL, NULL, NULL, NULL),
(23, 6, 1, 'TIPO_ENDERECO', NULL, NULL, NULL, NULL),
(24, 6, 2, 'COMPLEMENTO', NULL, NULL, NULL, NULL),
(25, 6, 6, 'PREFERENCIAL', NULL, NULL, NULL, NULL),
(26, 7, 1, 'ID_PESSOA', NULL, NULL, NULL, NULL),
(27, 7, 1, 'ID_PROFISSAO', NULL, NULL, NULL, NULL),
(28, 7, 1, 'TIPO_PESSOA', NULL, NULL, NULL, NULL),
(29, 7, 2, 'NOME', NULL, NULL, NULL, NULL),
(30, 7, 2, 'CPF_CNPJ', NULL, NULL, NULL, NULL),
(31, 7, 2, 'SEXO', NULL, NULL, NULL, NULL),
(32, 7, 5, 'RENDA', NULL, NULL, NULL, NULL),
(33, 7, 2, 'ESTADO_CIVIL', NULL, NULL, NULL, NULL),
(34, 7, 3, 'DATA_NASCIMENTO', NULL, NULL, NULL, NULL),
(35, 8, 1, 'ID_TELEFONE', NULL, NULL, NULL, NULL),
(36, 8, 1, 'ID_PESSOA', NULL, NULL, NULL, NULL),
(37, 8, 1, 'DDD', NULL, NULL, NULL, NULL),
(38, 8, 2, 'TELEFONE', NULL, NULL, NULL, NULL),
(39, 8, 1, 'TIPO', NULL, NULL, NULL, NULL),
(40, 8, 6, 'PREFERENCIAL', NULL, NULL, NULL, NULL),
(41, 8, 2, 'STATUS', NULL, NULL, NULL, NULL),
(42, 9, 1, 'ID_CATEGORIA', NULL, NULL, NULL, NULL),
(43, 9, 2, 'NOME_CATEGORIA', NULL, NULL, NULL, NULL),
(44, 10, 1, 'ID_PRODUTO', NULL, NULL, NULL, NULL),
(45, 10, 1, 'ID_CATEGORIA', NULL, NULL, NULL, NULL),
(46, 10, 2, 'PRODUTO', NULL, NULL, NULL, NULL),
(47, 10, 5, 'VALOR_VENDA', NULL, NULL, NULL, NULL),
(48, 11, 1, 'ID_COMPRA', NULL, NULL, NULL, NULL),
(49, 11, 3, 'DATA_PEDIDO', NULL, NULL, NULL, NULL),
(50, 11, 3, 'DATA_ENTRADA', NULL, NULL, NULL, NULL),
(51, 11, 1, 'ID_PESSOA', NULL, NULL, NULL, NULL),
(52, 12, 1, 'ID_ITEMCOMPRA', NULL, NULL, NULL, NULL),
(53, 12, 1, 'ID_COMPRA', NULL, NULL, NULL, NULL),
(54, 12, 1, 'ID_PRODUTO', NULL, NULL, NULL, NULL),
(55, 12, 1, 'QUANTIDADE', NULL, NULL, NULL, NULL),
(56, 12, 5, 'VLR_UNITARIO', NULL, NULL, NULL, NULL),
(57, 13, 1, 'ID_VENDA', NULL, NULL, NULL, NULL),
(58, 13, 1, 'ID_PESSOA', NULL, NULL, NULL, NULL),
(59, 13, 3, 'DATA_VENDA', NULL, NULL, NULL, NULL),
(60, 13, 3, 'DATA_FATURAMENTO', NULL, NULL, NULL, NULL),
(61, 13, 1, 'TIPO_VENDA', NULL, NULL, NULL, NULL),
(62, 14, 1, 'ID_ITEMVENDA', NULL, NULL, NULL, NULL),
(63, 14, 1, 'ID_VENDA', NULL, NULL, NULL, NULL),
(64, 14, 1, 'ID_PRODUTO', NULL, NULL, NULL, NULL),
(65, 14, 1, 'QUANTIDADE', NULL, NULL, NULL, NULL),
(66, 14, 5, 'VLR_UNITARIO', NULL, NULL, NULL, NULL),
(67, 15, 1, 'category_id', NULL, NULL, NULL, NULL),
(68, 15, 2, 'category_name', NULL, NULL, NULL, NULL),
(69, 15, 2, 'description', NULL, NULL, NULL, NULL),
(70, 15, 7, 'picture', NULL, NULL, NULL, NULL),
(71, 16, 2, 'customer_id', NULL, NULL, NULL, NULL),
(72, 16, 2, 'customer_type_id', NULL, NULL, NULL, NULL),
(73, 17, 2, 'customer_type_id', NULL, NULL, NULL, NULL),
(74, 17, 2, 'customer_desc', NULL, NULL, NULL, NULL),
(75, 18, 2, 'customer_id', NULL, NULL, NULL, NULL),
(76, 18, 2, 'company_name', NULL, NULL, NULL, NULL),
(77, 18, 2, 'contact_name', NULL, NULL, NULL, NULL),
(78, 18, 2, 'contact_title', NULL, NULL, NULL, NULL),
(79, 18, 2, 'address', NULL, NULL, NULL, NULL),
(80, 18, 2, 'city', NULL, NULL, NULL, NULL),
(81, 18, 2, 'region', NULL, NULL, NULL, NULL),
(82, 18, 2, 'postal_code', NULL, NULL, NULL, NULL),
(83, 18, 2, 'country', NULL, NULL, NULL, NULL),
(84, 18, 2, 'phone', NULL, NULL, NULL, NULL),
(85, 18, 2, 'fax', NULL, NULL, NULL, NULL),
(86, 19, 1, 'employee_id', NULL, NULL, NULL, NULL),
(87, 19, 2, 'last_name', NULL, NULL, NULL, NULL),
(88, 19, 2, 'first_name', NULL, NULL, NULL, NULL),
(89, 19, 2, 'title', NULL, NULL, NULL, NULL),
(90, 19, 2, 'title_of_courtesy', NULL, NULL, NULL, NULL),
(91, 19, 3, 'birth_date', NULL, NULL, NULL, NULL),
(92, 19, 3, 'hire_date', NULL, NULL, NULL, NULL),
(93, 19, 2, 'address', NULL, NULL, NULL, NULL),
(94, 19, 2, 'city', NULL, NULL, NULL, NULL),
(95, 19, 2, 'region', NULL, NULL, NULL, NULL),
(96, 19, 2, 'postal_code', NULL, NULL, NULL, NULL),
(97, 19, 2, 'country', NULL, NULL, NULL, NULL),
(98, 19, 2, 'home_phone', NULL, NULL, NULL, NULL),
(99, 19, 2, 'extension', NULL, NULL, NULL, NULL),
(100, 19, 7, 'photo', NULL, NULL, NULL, NULL),
(101, 19, 2, 'notes', NULL, NULL, NULL, NULL),
(102, 19, 1, 'reports_to', NULL, NULL, NULL, NULL),
(103, 19, 2, 'photo_path', NULL, NULL, NULL, NULL),
(104, 20, 1, 'employee_id', NULL, NULL, NULL, NULL),
(105, 20, 2, 'territory_id', NULL, NULL, NULL, NULL),
(106, 21, 1, 'order_id', NULL, NULL, NULL, NULL),
(107, 21, 1, 'product_id', NULL, NULL, NULL, NULL),
(108, 21, 5, 'unit_price', NULL, NULL, NULL, NULL),
(109, 21, 1, 'quantity', NULL, NULL, NULL, NULL),
(110, 21, 5, 'discount', NULL, NULL, NULL, NULL),
(111, 22, 1, 'order_id', NULL, NULL, NULL, NULL),
(112, 22, 2, 'customer_id', NULL, NULL, NULL, NULL),
(113, 22, 1, 'employee_id', NULL, NULL, NULL, NULL),
(114, 22, 3, 'order_date', NULL, NULL, NULL, NULL),
(115, 22, 3, 'required_date', NULL, NULL, NULL, NULL),
(116, 22, 3, 'shipped_date', NULL, NULL, NULL, NULL),
(117, 22, 1, 'ship_via', NULL, NULL, NULL, NULL),
(118, 22, 5, 'freight', NULL, NULL, NULL, NULL),
(119, 22, 2, 'ship_name', NULL, NULL, NULL, NULL),
(120, 22, 2, 'ship_address', NULL, NULL, NULL, NULL),
(121, 22, 2, 'ship_city', NULL, NULL, NULL, NULL),
(122, 22, 2, 'ship_region', NULL, NULL, NULL, NULL),
(123, 22, 2, 'ship_postal_code', NULL, NULL, NULL, NULL),
(124, 22, 2, 'ship_country', NULL, NULL, NULL, NULL),
(125, 23, 1, 'product_id', NULL, NULL, NULL, NULL),
(126, 23, 2, 'product_name', NULL, NULL, NULL, NULL),
(127, 23, 1, 'supplier_id', NULL, NULL, NULL, NULL),
(128, 23, 1, 'category_id', NULL, NULL, NULL, NULL),
(129, 23, 2, 'quantity_per_unit', NULL, NULL, NULL, NULL),
(130, 23, 5, 'unit_price', NULL, NULL, NULL, NULL),
(131, 23, 1, 'units_in_stock', NULL, NULL, NULL, NULL),
(132, 23, 1, 'units_on_order', NULL, NULL, NULL, NULL),
(133, 23, 1, 'reorder_level', NULL, NULL, NULL, NULL),
(134, 23, 1, 'discontinued', NULL, NULL, NULL, NULL),
(135, 24, 1, 'region_id', NULL, NULL, NULL, NULL),
(136, 24, 2, 'region_description', NULL, NULL, NULL, NULL),
(137, 25, 1, 'shipper_id', NULL, NULL, NULL, NULL),
(138, 25, 2, 'company_name', NULL, NULL, NULL, NULL),
(139, 25, 2, 'phone', NULL, NULL, NULL, NULL),
(140, 26, 1, 'supplier_id', NULL, NULL, NULL, NULL),
(141, 26, 2, 'company_name', NULL, NULL, NULL, NULL),
(142, 26, 2, 'contact_name', NULL, NULL, NULL, NULL),
(143, 26, 2, 'contact_title', NULL, NULL, NULL, NULL),
(144, 26, 2, 'address', NULL, NULL, NULL, NULL),
(145, 26, 2, 'city', NULL, NULL, NULL, NULL),
(146, 26, 2, 'region', NULL, NULL, NULL, NULL),
(147, 26, 2, 'postal_code', NULL, NULL, NULL, NULL),
(148, 26, 2, 'country', NULL, NULL, NULL, NULL),
(149, 26, 2, 'phone', NULL, NULL, NULL, NULL),
(150, 26, 2, 'fax', NULL, NULL, NULL, NULL),
(151, 26, 2, 'homepage', NULL, NULL, NULL, NULL),
(152, 27, 2, 'territory_id', NULL, NULL, NULL, NULL),
(153, 27, 2, 'territory_description', NULL, NULL, NULL, NULL),
(154, 27, 1, 'region_id', NULL, NULL, NULL, NULL),
(155, 28, 1, 'state_id', NULL, NULL, NULL, NULL),
(156, 28, 2, 'state_name', NULL, NULL, NULL, NULL),
(157, 28, 2, 'state_abbr', NULL, NULL, NULL, NULL),
(158, 28, 2, 'state_region', NULL, NULL, NULL, NULL);

INSERT INTO metadados.assunto_dw (id_assunto, nome_assunto, descricao) VALUES
(1, 'Dimensões Compartilhadas', 'Dimensões conformadas, reutilizadas por mais de um processo de negócio'),
(2, 'Vendas', 'Processo de venda de produtos a clientes'),
(3, 'Compras', 'Processo de compra de produtos de fornecedores (exclusivo da Mercearia)');

INSERT INTO metadados.tabela_dw (id_tabela_dw, id_assunto, nome_tabela, tipo_tabela, grao, periodicidade_carga) VALUES
(1, 1, 'dim_tempo', 'Dimensão', NULL, 'Diária'),
(2, 1, 'dim_enderecos', 'Dimensão', NULL, 'Diária'),
(3, 1, 'dim_produtos', 'Dimensão', NULL, 'Diária'),
(4, 1, 'dim_cliente', 'Dimensão', NULL, 'Diária'),
(5, 1, 'dim_funcionario', 'Dimensão', NULL, 'Diária'),
(6, 1, 'dim_transportadora', 'Dimensão', NULL, 'Diária'),
(7, 2, 'fato_vendas', 'Fato', '1 linha por produto vendido dentro de uma venda/pedido', 'Diária'),
(8, 3, 'fato_compras', 'Fato', '1 linha por produto comprado dentro de um pedido de compra', 'Diária');

INSERT INTO metadados.campo_dw (id_campo, id_tabela_dw, id_tipo_campo, nome_campo, descricao, papel_campo, tamanho_campo, casa_decimal) VALUES
(1, 1, 1, 'id_dim_tempo', NULL, 'PK', NULL, NULL),
(2, 1, 3, 'data', NULL, 'Atributo', NULL, NULL),
(3, 1, 1, 'dia', NULL, 'Atributo', NULL, NULL),
(4, 1, 1, 'mes', NULL, 'Atributo', NULL, NULL),
(5, 1, 2, 'nome_mes', NULL, 'Atributo', NULL, NULL),
(6, 1, 1, 'trimestre', NULL, 'Atributo', NULL, NULL),
(7, 1, 1, 'ano', NULL, 'Atributo', NULL, NULL),
(8, 1, 2, 'dia_semana', NULL, 'Atributo', NULL, NULL),
(9, 1, 6, 'flag_fim_semana', NULL, 'Atributo', NULL, NULL),
(10, 2, 1, 'id_dim_endereco', NULL, 'PK', NULL, NULL),
(11, 2, 2, 'sistema_origem', NULL, 'Atributo', NULL, NULL),
(12, 2, 2, 'id_endereco_original', NULL, 'Atributo', NULL, NULL),
(13, 2, 2, 'tipo_endereco', NULL, 'Atributo', NULL, NULL),
(14, 2, 2, 'nome_logradouro', NULL, 'Atributo', NULL, NULL),
(15, 2, 2, 'cep', NULL, 'Atributo', NULL, NULL),
(16, 2, 2, 'nome_bairro', NULL, 'Atributo', NULL, NULL),
(17, 2, 2, 'regiao_cidade', NULL, 'Atributo', NULL, NULL),
(18, 2, 2, 'nome_cidade', NULL, 'Atributo', NULL, NULL),
(19, 2, 2, 'nome_estado', NULL, 'Atributo', NULL, NULL),
(20, 2, 2, 'sigla_uf', NULL, 'Atributo', NULL, NULL),
(21, 2, 2, 'pais', NULL, 'Atributo', NULL, NULL),
(22, 2, 4, 'data_carga', NULL, 'Atributo', NULL, NULL),
(23, 3, 1, 'id_dim_produto', NULL, 'PK', NULL, NULL),
(24, 3, 2, 'sistema_origem', NULL, 'Atributo', NULL, NULL),
(25, 3, 2, 'id_produto_original', NULL, 'Atributo', NULL, NULL),
(26, 3, 2, 'nome_produto', NULL, 'Atributo', NULL, NULL),
(27, 3, 2, 'nome_categoria', NULL, 'Atributo', NULL, NULL),
(28, 3, 5, 'valor', NULL, 'Atributo', NULL, NULL),
(29, 3, 2, 'moeda', NULL, 'Atributo', NULL, NULL),
(30, 3, 4, 'data_carga', NULL, 'Atributo', NULL, NULL),
(31, 4, 1, 'id_dim_cliente', NULL, 'PK', NULL, NULL),
(32, 4, 2, 'sistema_origem', NULL, 'Atributo', NULL, NULL),
(33, 4, 2, 'id_cliente_original', NULL, 'Atributo', NULL, NULL),
(34, 4, 2, 'tipo_pessoa', NULL, 'Atributo', NULL, NULL),
(35, 4, 2, 'nome_cliente', NULL, 'Atributo', NULL, NULL),
(36, 4, 2, 'sexo', NULL, 'Atributo', NULL, NULL),
(37, 4, 2, 'faixa_renda', NULL, 'Atributo', NULL, NULL),
(38, 4, 2, 'estado_civil', NULL, 'Atributo', NULL, NULL),
(39, 4, 2, 'faixa_etaria', NULL, 'Atributo', NULL, NULL),
(40, 4, 1, 'ano_nascimento', NULL, 'Atributo', NULL, NULL),
(41, 4, 2, 'nome_profissao', NULL, 'Atributo', NULL, NULL),
(42, 4, 2, 'ddd_principal', NULL, 'Atributo', NULL, NULL),
(43, 4, 2, 'tipo_telefone', NULL, 'Atributo', NULL, NULL),
(44, 4, 4, 'data_carga', NULL, 'Atributo', NULL, NULL),
(45, 5, 1, 'id_dim_funcionario', NULL, 'PK', NULL, NULL),
(46, 5, 2, 'sistema_origem', NULL, 'Atributo', NULL, NULL),
(47, 5, 2, 'id_funcionario_original', NULL, 'Atributo', NULL, NULL),
(48, 5, 2, 'nome_funcionario', NULL, 'Atributo', NULL, NULL),
(49, 5, 2, 'cargo', NULL, 'Atributo', NULL, NULL),
(50, 5, 3, 'data_contratacao', NULL, 'Atributo', NULL, NULL),
(51, 5, 2, 'cidade', NULL, 'Atributo', NULL, NULL),
(52, 5, 2, 'pais', NULL, 'Atributo', NULL, NULL),
(53, 5, 4, 'data_carga', NULL, 'Atributo', NULL, NULL),
(54, 6, 1, 'id_dim_transportadora', NULL, 'PK', NULL, NULL),
(55, 6, 2, 'sistema_origem', NULL, 'Atributo', NULL, NULL),
(56, 6, 2, 'id_transportadora_original', NULL, 'Atributo', NULL, NULL),
(57, 6, 2, 'nome_transportadora', NULL, 'Atributo', NULL, NULL),
(58, 6, 2, 'telefone', NULL, 'Atributo', NULL, NULL),
(59, 6, 4, 'data_carga', NULL, 'Atributo', NULL, NULL),
(60, 7, 1, 'id_fato_venda', NULL, 'PK', NULL, NULL),
(61, 7, 2, 'sistema_origem', NULL, 'Atributo', NULL, NULL),
(62, 7, 2, 'id_venda_original', NULL, 'Atributo', NULL, NULL),
(63, 7, 2, 'id_item_original', NULL, 'Atributo', NULL, NULL),
(64, 7, 1, 'id_dim_tempo', NULL, 'FK', NULL, NULL),
(65, 7, 1, 'id_dim_cliente', NULL, 'FK', NULL, NULL),
(66, 7, 1, 'id_dim_produto', NULL, 'FK', NULL, NULL),
(67, 7, 1, 'id_dim_endereco', NULL, 'FK', NULL, NULL),
(68, 7, 1, 'id_dim_funcionario', NULL, 'FK', NULL, NULL),
(69, 7, 1, 'id_dim_transportadora', NULL, 'FK', NULL, NULL),
(70, 7, 2, 'tipo_venda', NULL, 'Atributo', NULL, NULL),
(71, 7, 1, 'quantidade', NULL, 'Atributo', NULL, NULL),
(72, 7, 5, 'valor_unitario', NULL, 'Atributo', NULL, NULL),
(73, 7, 5, 'valor_desconto', NULL, 'Atributo', NULL, NULL),
(74, 7, 5, 'valor_total_item', NULL, 'Atributo', NULL, NULL),
(75, 7, 4, 'data_carga', NULL, 'Atributo', NULL, NULL),
(76, 8, 1, 'id_fato_compra', NULL, 'PK', NULL, NULL),
(77, 8, 2, 'sistema_origem', NULL, 'Atributo', NULL, NULL),
(78, 8, 2, 'id_compra_original', NULL, 'Atributo', NULL, NULL),
(79, 8, 2, 'id_item_original', NULL, 'Atributo', NULL, NULL),
(80, 8, 1, 'id_dim_tempo', NULL, 'FK', NULL, NULL),
(81, 8, 1, 'id_dim_cliente', NULL, 'FK', NULL, NULL),
(82, 8, 1, 'id_dim_produto', NULL, 'FK', NULL, NULL),
(83, 8, 1, 'id_dim_endereco', NULL, 'FK', NULL, NULL),
(84, 8, 1, 'quantidade', NULL, 'Atributo', NULL, NULL),
(85, 8, 5, 'valor_unitario', NULL, 'Atributo', NULL, NULL),
(86, 8, 5, 'valor_total_item', NULL, 'Atributo', NULL, NULL),
(87, 8, 1, 'lead_time_dias', NULL, 'Atributo', NULL, NULL),
(88, 8, 4, 'data_carga', NULL, 'Atributo', NULL, NULL);

INSERT INTO metadados.dado_externo (id_dado_externo, nome_dado_externo, descricao, periodicidade) VALUES
(1, 'Calendário Gregoriano', 'Referência de datas usada para popular a dim_tempo via generate_series, sem vínculo com nenhum sistema transacional', 'Estática');

INSERT INTO metadados.dado_externo_conteudo (id_conteudo, id_dado_externo, conteudo, data, complemento) VALUES
(1, 1, '1996-01-01 a 2025-12-31', NULL, 'Intervalo coberto pela dim_tempo (cobre o período do Northwind e da Mercearia)');

INSERT INTO metadados.algoritmo_etl (id_algoritmo, nome_algoritmo, descricao, referencia_codigo) VALUES
(1, 'Geração de calendário via generate_series', 'Gera uma linha por dia no intervalo definido, extraindo dia/mês/ano/trimestre/dia da semana', 'scripts/dw_postgres.sql'),
(2, 'Atribuição de membro desconhecido (-1)', 'Usa a linha -1 (''Não aplicável'') da dimensão quando o sistema de origem não possui aquele conceito (ex: funcionário/transportadora na Mercearia)', 'scripts/dw_postgres.sql'),
(3, 'Marcação de sistema de origem', 'Grava qual sistema transacional originou a linha (Mercearia ou Northwind)', NULL),
(4, 'Bandeamento de faixa de renda', 'Converte o valor bruto de renda em uma faixa descritiva (ex: ''3 a 5 salários mínimos'')', NULL),
(5, 'Bandeamento de faixa etária', 'Converte a data de nascimento em uma faixa etária descritiva (ex: ''26-35'')', NULL),
(6, 'Resolução de chave substituta via lookup na dimensão conformada', 'Busca a chave substituta (surrogate key) na dimensão a partir do valor natural vindo do sistema transacional', NULL),
(7, 'Cálculo de valor total do item', 'quantidade × valor_unitário, descontando valor_desconto quando aplicável', NULL),
(8, 'Cálculo de lead time', 'Diferença em dias entre a data de entrada e a data do pedido', NULL),
(9, 'Concatenação de nome completo', 'Concatena first_name e last_name em um único campo de nome', NULL);

INSERT INTO metadados.integracao_transacional_dw (id_integracao, id_campo_transacional, id_campo_dw, id_dado_externo_conteudo, id_algoritmo) VALUES
(1, NULL, 2, 1, 1),
(2, NULL, 3, 1, 1),
(3, NULL, 4, 1, 1),
(4, NULL, 5, 1, 1),
(5, NULL, 6, 1, 1),
(6, NULL, 7, 1, 1),
(7, NULL, 8, 1, 1),
(8, NULL, 9, 1, 1),
(9, 20, 12, NULL, NULL),
(10, 23, 13, NULL, NULL),
(11, 15, 14, NULL, NULL),
(12, 16, 15, NULL, NULL),
(13, 10, 16, NULL, NULL),
(14, 11, 17, NULL, NULL),
(15, 5, 18, NULL, NULL),
(16, 2, 19, NULL, NULL),
(17, 3, 20, NULL, NULL),
(18, 75, 12, NULL, NULL),
(19, 79, 14, NULL, NULL),
(20, 82, 15, NULL, NULL),
(21, 81, 17, NULL, NULL),
(22, 80, 18, NULL, NULL),
(23, 83, 21, NULL, NULL),
(24, 44, 25, NULL, NULL),
(25, 46, 26, NULL, NULL),
(26, 43, 27, NULL, NULL),
(27, 47, 28, NULL, NULL),
(28, 125, 25, NULL, NULL),
(29, 126, 26, NULL, NULL),
(30, 68, 27, NULL, NULL),
(31, 130, 28, NULL, NULL),
(32, 26, 33, NULL, NULL),
(33, 28, 34, NULL, NULL),
(34, 29, 35, NULL, NULL),
(35, 31, 36, NULL, NULL),
(36, 32, 37, NULL, 4),
(37, 33, 38, NULL, NULL),
(38, 34, 39, NULL, 5),
(39, 34, 40, NULL, NULL),
(40, 8, 41, NULL, NULL),
(41, 37, 42, NULL, NULL),
(42, 39, 43, NULL, NULL),
(43, 75, 33, NULL, NULL),
(44, 76, 35, NULL, NULL),
(45, 78, 41, NULL, NULL),
(46, 86, 47, NULL, NULL),
(47, 88, 48, NULL, 9),
(48, 87, 48, NULL, 9),
(49, 89, 49, NULL, NULL),
(50, 92, 50, NULL, NULL),
(51, 94, 51, NULL, NULL),
(52, 97, 52, NULL, NULL),
(53, 137, 56, NULL, NULL),
(54, 138, 57, NULL, NULL),
(55, 139, 58, NULL, NULL),
(56, 57, 62, NULL, NULL),
(57, 62, 63, NULL, NULL),
(58, 59, 64, NULL, 6),
(59, 58, 65, NULL, 6),
(60, 64, 66, NULL, 6),
(61, 58, 67, NULL, 6),
(62, 61, 70, NULL, NULL),
(63, 65, 71, NULL, NULL),
(64, 66, 72, NULL, NULL),
(65, 65, 74, NULL, 7),
(66, 66, 74, NULL, 7),
(67, 111, 62, NULL, NULL),
(68, 114, 64, NULL, 6),
(69, 112, 65, NULL, 6),
(70, 107, 66, NULL, 6),
(71, 112, 67, NULL, 6),
(72, 113, 68, NULL, 6),
(73, 117, 69, NULL, 6),
(74, 109, 71, NULL, NULL),
(75, 108, 72, NULL, NULL),
(76, 110, 73, NULL, NULL),
(77, 109, 74, NULL, 7),
(78, 108, 74, NULL, 7),
(79, 110, 74, NULL, 7),
(80, 48, 78, NULL, NULL),
(81, 52, 79, NULL, NULL),
(82, 49, 80, NULL, 6),
(83, 51, 81, NULL, 6),
(84, 54, 82, NULL, 6),
(85, 51, 83, NULL, 6),
(86, 55, 84, NULL, NULL),
(87, 56, 85, NULL, NULL),
(88, 55, 86, NULL, 7),
(89, 56, 86, NULL, 7),
(90, 49, 87, NULL, 8),
(91, 50, 87, NULL, 8);
