CREATE DATABASE dw;

\c dw

CREATE SCHEMA corporativo;

-- ----------------------------
-- ASSUNTO: TEMPO
-- ----------------------------
-- Calendário corporativo, gerado uma vez (não vem de sistema
-- transacional). Compartilhado por todos os assuntos, igual a
-- Geografia — por isso fica antes dos demais.

CREATE TABLE corporativo.tempos (
    id_tempo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    dia INT NOT NULL,
    mes INT NOT NULL,
    nome_mes VARCHAR(20) NOT NULL,
    trimestre INT NOT NULL,
    ano INT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    flag_fim_semana BOOLEAN NOT NULL,
    UNIQUE (data)
);

INSERT INTO corporativo.tempos (data, dia, mes, nome_mes, trimestre, ano, dia_semana, flag_fim_semana)
SELECT
    d::date,
    EXTRACT(DAY FROM d)::int,
    EXTRACT(MONTH FROM d)::int,
    TO_CHAR(d, 'TMMonth'),
    EXTRACT(QUARTER FROM d)::int,
    EXTRACT(YEAR FROM d)::int,
    TO_CHAR(d, 'TMDay'),
    EXTRACT(ISODOW FROM d) IN (6, 7)
FROM generate_series('1996-01-01'::date, '2035-12-31'::date, interval '1 day') AS d;

-- ----------------------------
-- ASSUNTO: GEOGRAFIA
-- ----------------------------

CREATE TABLE corporativo.paises (
    id_pais INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE TABLE corporativo.estados (
    id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(10) NOT NULL,
    id_pais INT NOT NULL REFERENCES corporativo.paises (id_pais),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_pais, sigla)
);

CREATE TABLE corporativo.cidades (
    id_cidade INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    regiao VARCHAR(255),
    id_estado INT NOT NULL REFERENCES corporativo.estados (id_estado),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_estado, nome)
);

CREATE TABLE corporativo.enderecos (
    id_endereco INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_endereco_origem VARCHAR(50),
    tipo_endereco VARCHAR(45),
    logradouro VARCHAR(255),
    cep VARCHAR(20),
    bairro VARCHAR(255),
    id_cidade INT NOT NULL REFERENCES corporativo.cidades (id_cidade),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_endereco_origem)
);

-- ----------------------------
-- ASSUNTO: PESSOAS
-- ----------------------------

CREATE TABLE corporativo.profissoes (
    id_profissao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE SEQUENCE corporativo.seq_clientes START 1;

CREATE TABLE corporativo.clientes (
    id_cliente INT NOT NULL DEFAULT nextval('corporativo.seq_clientes'),
    data_inicio_validade DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fim_validade DATE,
    flag_atual BOOLEAN NOT NULL DEFAULT TRUE,
    sistema_origem VARCHAR(20) NOT NULL,
    id_cliente_origem VARCHAR(50) NOT NULL,
    tipo_pessoa VARCHAR(20) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    sexo VARCHAR(20),
    estado_civil VARCHAR(45),
    ano_nascimento INT,
    faixa_renda VARCHAR(50),
    id_profissao INT REFERENCES corporativo.profissoes (id_profissao),
    id_endereco INT REFERENCES corporativo.enderecos (id_endereco),
    ddd_telefone VARCHAR(10),
    numero_telefone VARCHAR(20),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (id_cliente, data_inicio_validade),
    UNIQUE (sistema_origem, id_cliente_origem, data_inicio_validade)
);

CREATE TABLE corporativo.cargos (
    id_cargo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE SEQUENCE corporativo.seq_funcionarios START 1;

CREATE TABLE corporativo.funcionarios (
    id_funcionario INT NOT NULL DEFAULT nextval('corporativo.seq_funcionarios'),
    data_inicio_validade DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fim_validade DATE,
    flag_atual BOOLEAN NOT NULL DEFAULT TRUE,
    sistema_origem VARCHAR(20) NOT NULL,
    id_funcionario_origem VARCHAR(50),
    nome VARCHAR(255) NOT NULL,
    data_contratacao DATE,
    id_cargo INT REFERENCES corporativo.cargos (id_cargo),
    id_endereco INT REFERENCES corporativo.enderecos (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (id_funcionario, data_inicio_validade),
    UNIQUE (sistema_origem, id_funcionario_origem, data_inicio_validade)
);

INSERT INTO corporativo.funcionarios (id_funcionario, sistema_origem, id_funcionario_origem, nome)
VALUES (-1, 'N/A', NULL, 'Não aplicável');

-- ----------------------------
-- ASSUNTO: PRODUTO E PARCEIROS
-- ----------------------------

CREATE TABLE corporativo.categorias (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE SEQUENCE corporativo.seq_produtos START 1;

CREATE TABLE corporativo.produtos (
    id_produto INT NOT NULL DEFAULT nextval('corporativo.seq_produtos'),
    data_inicio_validade DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fim_validade DATE,
    flag_atual BOOLEAN NOT NULL DEFAULT TRUE,
    sistema_origem VARCHAR(20) NOT NULL,
    id_produto_origem VARCHAR(50) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    valor NUMERIC(15,2),
    moeda CHAR(3) NOT NULL DEFAULT 'BRL',
    id_categoria INT REFERENCES corporativo.categorias (id_categoria),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (id_produto, data_inicio_validade),
    UNIQUE (sistema_origem, id_produto_origem, data_inicio_validade)
);

CREATE TABLE corporativo.transportadoras (
    id_transportadora INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_transportadora_origem VARCHAR(50),
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(50),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_transportadora_origem)
);

INSERT INTO corporativo.transportadoras (id_transportadora, sistema_origem, id_transportadora_origem, nome)
VALUES (-1, 'N/A', NULL, 'Não aplicável');

CREATE TABLE corporativo.fornecedores (
    id_fornecedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_fornecedor_origem VARCHAR(50),
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(50),
    id_endereco INT REFERENCES corporativo.enderecos (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_fornecedor_origem)
);

-- ----------------------------
-- ASSUNTO: TRANSAÇÕES
-- ----------------------------

CREATE TABLE corporativo.vendas (
    id_venda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_venda_origem VARCHAR(50) NOT NULL,
    id_tempo INT NOT NULL REFERENCES corporativo.tempos (id_tempo),
    tipo_venda VARCHAR(50),
    id_cliente INT NOT NULL, -- junção temporal com corporativo.clientes (id_cliente + data do id_tempo dentro da validade), não FK simples
    id_funcionario INT NOT NULL DEFAULT -1, -- junção temporal com corporativo.funcionarios
    id_transportadora INT NOT NULL DEFAULT -1 REFERENCES corporativo.transportadoras (id_transportadora),
    id_endereco_entrega INT REFERENCES corporativo.enderecos (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_venda_origem)
);

CREATE INDEX idx_venda_cliente ON corporativo.vendas (id_cliente);
CREATE INDEX idx_venda_funcionario ON corporativo.vendas (id_funcionario);
CREATE INDEX idx_venda_tempo ON corporativo.vendas (id_tempo);

CREATE TABLE corporativo.itens_vendas (
    id_item_venda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_item_origem VARCHAR(50),
    id_venda BIGINT NOT NULL REFERENCES corporativo.vendas (id_venda),
    id_produto INT NOT NULL, -- junção temporal com corporativo.produtos (id_produto + data do id_tempo da venda), não FK simples
    quantidade INT NOT NULL,
    valor_unitario NUMERIC(15,2) NOT NULL,
    valor_desconto NUMERIC(15,2) NOT NULL DEFAULT 0,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_item_venda_venda ON corporativo.itens_vendas (id_venda);
CREATE INDEX idx_item_venda_produto ON corporativo.itens_vendas (id_produto);

CREATE TABLE corporativo.compras (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL DEFAULT 'Mercearia',
    id_compra_origem VARCHAR(50) NOT NULL,
    id_tempo INT NOT NULL REFERENCES corporativo.tempos (id_tempo),
    lead_time_dias INT,
    id_fornecedor INT REFERENCES corporativo.fornecedores (id_fornecedor),
    id_endereco INT REFERENCES corporativo.enderecos (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_compra_origem)
);

CREATE INDEX idx_compra_fornecedor ON corporativo.compras (id_fornecedor);
CREATE INDEX idx_compra_tempo ON corporativo.compras (id_tempo);

CREATE TABLE corporativo.itens_compras (
    id_item_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_item_origem VARCHAR(50),
    id_compra BIGINT NOT NULL REFERENCES corporativo.compras (id_compra),
    id_produto INT NOT NULL, -- junção temporal com corporativo.produtos (id_produto + data do id_tempo da compra), não FK simples
    quantidade INT NOT NULL,
    valor_unitario NUMERIC(15,2) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_item_compra_compra ON corporativo.itens_compras (id_compra);
CREATE INDEX idx_item_compra_produto ON corporativo.itens_compras (id_produto);
