CREATE DATABASE dw;

\c dw

CREATE SCHEMA corporativo;

-- ============================================================
-- DW normalizado (Inmon): orientado a assunto, integrado,
-- não-volátil, variante no tempo.
--
-- Integrado: cada entidade que vem de sistema transacional traz
-- sistema_origem + id_..._origem, resolvendo Northwind/Mercearia
-- para uma única chave corporativa (id_..., sequência própria).
--
-- Não-volátil / variante no tempo: Cliente, Funcionario e Produto
-- nunca sofrem UPDATE nos atributos versionados — uma mudança
-- insere uma nova linha (data_inicio_validade/data_fim_validade/
-- flag_atual), preservando o histórico. Por isso a PK dessas
-- tabelas é composta (id_natural, data_inicio_validade).
--
-- Como Venda/ItemVenda/Compra/ItemCompra guardam só o id natural
-- (não a versão), a ligação com Cliente/Funcionario/Produto é uma
-- junção temporal (id + data do evento dentro do intervalo de
-- validade), não uma FK simples — por isso essas colunas não têm
-- REFERENCES formal, só comentário.
-- ============================================================

-- ----------------------------
-- ASSUNTO: GEOGRAFIA
-- ----------------------------

CREATE TABLE corporativo.pais (
    id_pais INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE TABLE corporativo.estado (
    id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(10) NOT NULL,
    id_pais INT NOT NULL REFERENCES corporativo.pais (id_pais),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_pais, sigla)
);

CREATE TABLE corporativo.cidade (
    id_cidade INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    regiao VARCHAR(255),
    id_estado INT NOT NULL REFERENCES corporativo.estado (id_estado),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_estado, nome)
);

CREATE TABLE corporativo.endereco (
    id_endereco INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_endereco_origem VARCHAR(50),
    tipo_endereco VARCHAR(45),
    logradouro VARCHAR(255),
    cep VARCHAR(20),
    bairro VARCHAR(255),
    id_cidade INT NOT NULL REFERENCES corporativo.cidade (id_cidade),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_endereco_origem)
);

-- ----------------------------
-- ASSUNTO: PESSOAS
-- ----------------------------

CREATE TABLE corporativo.profissao (
    id_profissao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE SEQUENCE corporativo.seq_cliente START 1;

CREATE TABLE corporativo.cliente (
    id_cliente INT NOT NULL DEFAULT nextval('corporativo.seq_cliente'),
    data_inicio_validade DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fim_validade DATE,
    flag_atual BOOLEAN NOT NULL DEFAULT TRUE,
    sistema_origem VARCHAR(20) NOT NULL,
    id_cliente_origem VARCHAR(50) NOT NULL,
    tipo_pessoa VARCHAR(20) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    sexo VARCHAR(20),
    estado_civil VARCHAR(45),
    ano_nascimento INT,
    faixa_renda VARCHAR(50),
    id_profissao INT REFERENCES corporativo.profissao (id_profissao),
    id_endereco INT REFERENCES corporativo.endereco (id_endereco),
    ddd_telefone VARCHAR(10),
    numero_telefone VARCHAR(20),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (id_cliente, data_inicio_validade),
    UNIQUE (sistema_origem, id_cliente_origem, data_inicio_validade)
);

CREATE TABLE corporativo.cargo (
    id_cargo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE SEQUENCE corporativo.seq_funcionario START 1;

CREATE TABLE corporativo.funcionario (
    id_funcionario INT NOT NULL DEFAULT nextval('corporativo.seq_funcionario'),
    data_inicio_validade DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fim_validade DATE,
    flag_atual BOOLEAN NOT NULL DEFAULT TRUE,
    sistema_origem VARCHAR(20) NOT NULL,
    id_funcionario_origem VARCHAR(50),
    nome VARCHAR(255) NOT NULL,
    data_contratacao DATE,
    id_cargo INT REFERENCES corporativo.cargo (id_cargo),
    id_endereco INT REFERENCES corporativo.endereco (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (id_funcionario, data_inicio_validade),
    UNIQUE (sistema_origem, id_funcionario_origem, data_inicio_validade)
);

INSERT INTO corporativo.funcionario (id_funcionario, sistema_origem, id_funcionario_origem, nome)
VALUES (-1, 'N/A', NULL, 'Não aplicável');

-- ----------------------------
-- ASSUNTO: PRODUTO E PARCEIROS
-- ----------------------------

CREATE TABLE corporativo.categoria (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome)
);

CREATE SEQUENCE corporativo.seq_produto START 1;

CREATE TABLE corporativo.produto (
    id_produto INT NOT NULL DEFAULT nextval('corporativo.seq_produto'),
    data_inicio_validade DATE NOT NULL DEFAULT CURRENT_DATE,
    data_fim_validade DATE,
    flag_atual BOOLEAN NOT NULL DEFAULT TRUE,
    sistema_origem VARCHAR(20) NOT NULL,
    id_produto_origem VARCHAR(50) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    valor NUMERIC(15,2),
    moeda CHAR(3) NOT NULL DEFAULT 'BRL',
    id_categoria INT REFERENCES corporativo.categoria (id_categoria),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (id_produto, data_inicio_validade),
    UNIQUE (sistema_origem, id_produto_origem, data_inicio_validade)
);

CREATE TABLE corporativo.transportadora (
    id_transportadora INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_transportadora_origem VARCHAR(50),
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(50),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_transportadora_origem)
);

INSERT INTO corporativo.transportadora (id_transportadora, sistema_origem, id_transportadora_origem, nome)
VALUES (-1, 'N/A', NULL, 'Não aplicável');

CREATE TABLE corporativo.fornecedor (
    id_fornecedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_fornecedor_origem VARCHAR(50),
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(50),
    id_endereco INT REFERENCES corporativo.endereco (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_fornecedor_origem)
);

-- ----------------------------
-- ASSUNTO: TRANSAÇÕES
-- ----------------------------

CREATE TABLE corporativo.venda (
    id_venda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_venda_origem VARCHAR(50) NOT NULL,
    data_venda DATE NOT NULL,
    tipo_venda VARCHAR(50),
    id_cliente INT NOT NULL, -- junção temporal com corporativo.cliente (id_cliente + data_venda dentro da validade), não FK simples
    id_funcionario INT NOT NULL DEFAULT -1, -- junção temporal com corporativo.funcionario
    id_transportadora INT NOT NULL DEFAULT -1 REFERENCES corporativo.transportadora (id_transportadora),
    id_endereco_entrega INT REFERENCES corporativo.endereco (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_venda_origem)
);

CREATE INDEX idx_venda_cliente ON corporativo.venda (id_cliente);
CREATE INDEX idx_venda_funcionario ON corporativo.venda (id_funcionario);
CREATE INDEX idx_venda_data ON corporativo.venda (data_venda);

CREATE TABLE corporativo.item_venda (
    id_item_venda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_item_origem VARCHAR(50),
    id_venda BIGINT NOT NULL REFERENCES corporativo.venda (id_venda),
    id_produto INT NOT NULL, -- junção temporal com corporativo.produto (id_produto + data_venda), não FK simples
    quantidade INT NOT NULL,
    valor_unitario NUMERIC(15,2) NOT NULL,
    valor_desconto NUMERIC(15,2) NOT NULL DEFAULT 0,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_item_venda_venda ON corporativo.item_venda (id_venda);
CREATE INDEX idx_item_venda_produto ON corporativo.item_venda (id_produto);

CREATE TABLE corporativo.compra (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL DEFAULT 'Mercearia',
    id_compra_origem VARCHAR(50) NOT NULL,
    data_compra DATE NOT NULL,
    lead_time_dias INT,
    id_fornecedor INT REFERENCES corporativo.fornecedor (id_fornecedor),
    id_endereco INT REFERENCES corporativo.endereco (id_endereco),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_compra_origem)
);

CREATE INDEX idx_compra_fornecedor ON corporativo.compra (id_fornecedor);
CREATE INDEX idx_compra_data ON corporativo.compra (data_compra);

CREATE TABLE corporativo.item_compra (
    id_item_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_item_origem VARCHAR(50),
    id_compra BIGINT NOT NULL REFERENCES corporativo.compra (id_compra),
    id_produto INT NOT NULL, -- junção temporal com corporativo.produto (id_produto + data_compra), não FK simples
    quantidade INT NOT NULL,
    valor_unitario NUMERIC(15,2) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_item_compra_compra ON corporativo.item_compra (id_compra);
CREATE INDEX idx_item_compra_produto ON corporativo.item_compra (id_produto);
